class_name NCONSTANTS2

enum {  CFI_TIMESTAMP 		= -1, 
		CFI_TIMESTAMPPREV 	= -2,
		
		CFI_PLAYER_NODENAME	= -3,
		CFI_TIMESTAMP_F0 	= -4,
		CFI_TIMESTAMP_RECIEVED = -5, 
		CFI_ZERO = 0,
		
		CFI_VRORIGIN_POSITION = 50,
		CFI_VRORIGIN_ROTATION = 51,
		CFI_VRHEAD_POSITION = 60,
		CFI_VRHEAD_ROTATION = 61,
		
		CFI_VRCONTROLLERLEFT_VISIBLE = 70,
		CFI_VRCONTROLLERLEFT_POSITION = 71,
		CFI_VRCONTROLLERLEFT_ROTATION = 72,
		CFI_VRCONTROLLERRIGHT_VISIBLE = 80,
		CFI_VRCONTROLLERRIGHT_POSITION = 81,
		CFI_VRCONTROLLERRIGHT_ROTATION = 82,

		CFI_VRHANDLEFT_VISIBLE = 110,
		CFI_VRHANDLEFT_POSITION = 111,
		CFI_VRHANDLEFT_ROTATION = 112,
		CFI_VRHANDRIGHT_VISIBLE = 130,
		CFI_VRHANDRIGHT_POSITION = 131,
		CFI_VRHANDRIGHT_ROTATION = 132,
		
		CFI_VRHANDLEFT_POSE = 73,
		CFI_VRHANDRIGHT_POSE = 83,
		
		CFI_AVATAR_POSE = 89,
		CFI_AVATAR_ADD_AMOUNT = 90,
		CFI_AVATAR_SKELETONIKLEGL_TARGET_POSITION = 91,
		CFI_AVATAR_SKELETONIKLEGL_TARGET_ROTATION = 92,
		CFI_AVATAR_SKELETONIKLEGR_TARGET_POSITION = 93,
		CFI_AVATAR_SKELETONIKLEGR_TARGET_ROTATION = 94,
		CFI_AVATAR_POSITION = 95
		CFI_AVATAR_ROTATION = 96
		CFI_AVATAR_ARMATURE_POSITION = 97,
		CFI_AVATAR_ARMATURE_ROTATION = 98,
		CFI_AVATAR_SKELETONIKHEAD_POSE_POSITION = 99,
		CFI_AVATAR_SKELETONIKHEAD_POSE_ROTATION = 100

				
	 }
